# Generated by Django 4.1.7 on 2023-03-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
